source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'MMStackView_Example', :exclusive => true do
  pod "MMStackView", :path => "../"
end

target 'MMStackView_Tests', :exclusive => true do
  pod "MMStackView", :path => "../"

  
end
